"""Prepare original v0.8 beta.2 inputs, without answers or generated diagrams.

Only Python's standard library is required. No project hook or vendor process
is executed. Inputs are excerpts, not vendor-generated or buildable projects.
The separate review rubric is deliberately not part of this public fixture.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import textwrap


def excerpt(value: str) -> str:
    return textwrap.dedent(value).strip() + "\n"


ORIGIN = excerpt("""
    # 材料身份
    本目录是原创合成工程摘录，用于独立接手与规划演练；不是厂商生成树，
    不包含 SDK、厂商库或可直接构建的完整工程。引脚声明来自本材料，未通过
    实物接线、封装检查或板测验证。源码中的外部函数由接口说明限定其行为。
    不提供解题图、评分答案或历史试验输出。没有运行厂商生成或构建。
""")


def case(case_id: str, title: str, kind: str, request: str,
         files: dict[str, str], writable: list[str] | None = None) -> dict:
    return {"id": case_id, "title": title, "kind": kind, "request": request,
            "native_generated": False,
            "allowed_source_edits": writable or [],
            "files": {**files, "MATERIAL_ORIGIN.md": ORIGIN}}


def build_cases() -> list[dict]:
    result = []
    result.append(case("01-baremetal-plan", "串口命令与定时输出的裸机工程",
        "baremetal-planning",
        "根据当前目录材料，为这套裸机命令控制与传感器回传工程完成整体规划，交付配套的引脚功能图和执行逻辑图，并说明尚未确定的部分。输入材料保持不变；规划文件写到 planning/。不运行厂商工具，不操作硬件。", {
        "CommandSampler.ioc": excerpt("""
            # Original source excerpt; not generated by CubeMX.
            File.Version=6
            MxCube.Version=6.18.1
            Mcu.CPN=STM32F103C8T6
            Mcu.Package=LQFP48
            Mcu.IP0=USART1
            Mcu.IP1=SPI1
            Mcu.IP2=TIM4
            Mcu.IP3=DMA
            Mcu.IPNb=4
            PA9.Signal=USART1_TX
            PA10.Signal=USART1_RX
            PA5.Signal=SPI1_SCK
            PA6.Signal=SPI1_MISO
            PA7.Signal=SPI1_MOSI
            PB0.Signal=GPIO_Output
            PB0.GPIO_Label=SENSOR_CS_N
            PB6.Signal=TIM4_CH1
            PC13-TAMPER-RTC.Signal=GPIO_Output
            PC13-TAMPER-RTC.GPIO_Label=ALIVE_LED
            PA13.Signal=SYS_JTMS-SWDIO
            PA14.Signal=SYS_JTCK-SWCLK
            USART1.BaudRate=115200
            USART1.RX_DMA=DMA1_Channel5
            USART1.RX_DMAMode=Circular
            ProjectManager.ProjectName=CommandSampler
            ProjectManager.ToolChain=CMake
        """),
        "APP/profile.h": excerpt("""
            #define SENSOR_INTERVAL_MS 20U
            #define REPORT_INTERVAL_MS 100U
            #define ALIVE_INTERVAL_MS 500U
            #define PWM_FREQUENCY_HZ 1000U
            #define COMMAND_DMA_BYTES 64U
        """),
        "Core/Src/main.c": excerpt("""
            /* Source excerpt: all main-loop timestamps use the HAL ms tick. */
            void app_start(void) {
                board_init();
                HAL_UART_Receive_DMA(&huart1, command_ring, COMMAND_DMA_BYTES);
                start_pwm_tim4_ch1(PWM_FREQUENCY_HZ, 0U);
                uint32_t sensor_at = HAL_GetTick();
                uint32_t report_at = sensor_at;
                uint32_t alive_at = sensor_at;
                for (;;) {
                    uint32_t now = HAL_GetTick();
                    command_t command;
                    while (parser_take_complete_command(&command)) {
                        apply_pwm_compare(command.duty_permille);
                    }
                    if ((uint32_t)(now - sensor_at) >= SENSOR_INTERVAL_MS) {
                        sensor_at = now;
                        snapshot = read_spi1_sensor_once();
                    }
                    if ((uint32_t)(now - report_at) >= REPORT_INTERVAL_MS) {
                        report_at = now;
                        if (!start_uart1_report_it(&snapshot)) ++report_skipped;
                    }
                    if ((uint32_t)(now - alive_at) >= ALIVE_INTERVAL_MS) {
                        alive_at = now;
                        toggle_alive_led();
                    }
                }
            }
        """),
        "Core/Src/uart_callbacks.c": excerpt("""
            /* RX DMA half/full notifications publish producer positions only. */
            void HAL_UART_RxHalfCpltCallback(UART_HandleTypeDef *h) {
                if (h == &huart1) command_rx_publish_position(32U);
            }
            void HAL_UART_RxCpltCallback(UART_HandleTypeDef *h) {
                if (h == &huart1) command_rx_publish_position(0U);
            }
            void HAL_UART_TxCpltCallback(UART_HandleTypeDef *h) {
                if (h == &huart1) report_tx_busy = false;
            }
        """),
        "CONTRACTS.md": excerpt("""
            # 已有接口与范围
            外部模块：主机串口、全双工 SPI 传感器、PWM 输入的执行器、状态 LED。
            传感器 CS_N 低有效；SPI 的 MISO 是传感器到 MCU，MOSI 反向。
            TIM4_CH1 由硬件持续输出 1 kHz PWM。主循环只按命令更新比较值，
            不要求每个 PWM 周期进入中断。没有 RTOS，也没有显示屏。

            DMA1_Channel5 循环写 64 字节接收环。half/full 回调只提交位置；
            主循环 parser_take_complete_command 消费环中数据并解析完整命令。
            环溢出检测在 parser 内部，此摘录不提供其实现；不声称无丢包。
            read_spi1_sensor_once 是有界阻塞 SPI 交易，具体耗时待测。
            start_uart1_report_it 在 TX 空闲时复制快照并启动中断发送；忙时返回
            false，不覆盖在途缓冲，也不补发错过的报告。TX 未使用 DMA。
            各定时分支按当前时刻更新时间戳，迟到只执行一次；不是精确硬实时周期。
            当前没有看门狗、ADC、额外中断采样或 CPU 执行时间证据。
            封装脚号、连接器端子与真实板卡型号尚未提供。
        """),
    }))

    result.append(case("02-rtos-plan", "当前 RTOS 流处理与历史副本",
        "rtos-current-revision-planning",
        "接续 flow-control-29，按 current/ 下已经保存的结构完成整体规划和两张工程图，说明任务如何接收、处理和显示数据。旧材料留作历史，不改输入文件。规划输出放 planning/；本次不生成、构建或操作硬件。", {
        "SCOPE.md": excerpt("""
            # 当前任务
            当前身份：flow-control-29，入口 current/FlowController.ioc，版本 r6。
            archive/r3 是旧的 flow-control-11。其文件在整理归档时被再次保存，
            所以 modified 字段更晚；当前入口由本记录指定。
            本轮已委托在 current 的既有结构内做整体规划，无原生生成或板测任务。
        """),
        "current/FlowController.ioc": excerpt("""
            # Original IOC excerpt; configuration fields are test source material.
            File.Version=6
            MxCube.Version=6.18.1
            Mcu.CPN=STM32G474RET6
            Mcu.Package=LQFP64
            Mcu.IP0=FREERTOS
            Mcu.IP1=USART2
            Mcu.IP2=I2C1
            Mcu.IP3=TIM1
            Mcu.IP4=DMA
            Mcu.IPNb=5
            PA2.Signal=USART2_TX
            PA3.Signal=USART2_RX
            PB6.Signal=I2C1_SCL
            PB7.Signal=I2C1_SDA
            PA8.Signal=TIM1_CH1
            PC13.Signal=GPIO_Output
            PC13.GPIO_Label=LINK_LED
            FREERTOS.Tasks01=FrameDecode,32,384,FrameDecode_Entry,As external,NULL,Static,FrameStack,FrameTCB;ControlApply,40,512,ControlApply_Entry,As external,NULL,Dynamic,NULL,NULL;PanelRender,24,384,PanelRender_Entry,As external,NULL,Static,PanelStack,PanelTCB
            FREERTOS.Queues01=FrameQueue,4,SensorFrame_t,0,Static,FrameQueueBuffer,FrameQueueCB
            ProjectManager.ProjectName=FlowController
            ProjectManager.ToolChain=MDK-ARM V5
        """),
        "current/Core/Inc/FreeRTOSConfig.h": excerpt("""
            #define configTICK_RATE_HZ 250U
            #define configMAX_PRIORITIES 56U
            #define configSUPPORT_STATIC_ALLOCATION 1
            #define configSUPPORT_DYNAMIC_ALLOCATION 1
        """),
        "current/APP/profile.h": excerpt("""
            #define CONTROL_WAIT_TICKS 10U
            #define PANEL_DELAY_TICKS 8U
            #define RX_POSITION_FLAG 1U
            #define LINK_PWM_HZ 2000U
        """),
        "current/APP/tasks.c": excerpt("""
            /* All queue and mutex handles are generated once before kernel start. */
            void FrameDecode_Entry(void *argument) {
                SensorFrame_t frame;
                for (;;) {
                    osThreadFlagsWait(RX_POSITION_FLAG, osFlagsWaitAny, osWaitForever);
                    while (take_validated_rx_frame(&frame)) {
                        if (osMessageQueuePut(FrameQueueHandle, &frame, 0U, 0U) != osOK)
                            ++frame_queue_drops;
                    }
                }
            }
            void ControlApply_Entry(void *argument) {
                SensorFrame_t frame;
                for (;;) {
                    osStatus_t result = osMessageQueueGet(FrameQueueHandle, &frame,
                                                          NULL, CONTROL_WAIT_TICKS);
                    if (result == osOK) apply_frame_to_pwm_and_snapshot(&frame);
                    else if (result == osErrorTimeout) mark_link_timeout_in_snapshot();
                    else record_queue_error(result);
                }
            }
            void PanelRender_Entry(void *argument) {
                for (;;) {
                    osDelay(PANEL_DELAY_TICKS);
                    UiSnapshot snapshot = copy_snapshot_under_state_lock();
                    draw_i2c_panel(&snapshot);
                }
            }
            void HAL_UART_RxHalfCpltCallback(UART_HandleTypeDef *handle) {
                if (handle == &huart2) {
                    rx_publish_dma_position(64U);
                    osThreadFlagsSet(FrameDecodeHandle, RX_POSITION_FLAG);
                }
            }
            void HAL_UART_RxCpltCallback(UART_HandleTypeDef *handle) {
                if (handle == &huart2) {
                    rx_publish_dma_position(0U);
                    osThreadFlagsSet(FrameDecodeHandle, RX_POSITION_FLAG);
                }
            }
        """),
        "current/INTERFACES.md": excerpt("""
            # 当前接口契约 r6
            内核为 FreeRTOS，ST CMSIS-RTOS2 适配；给出的优先级字段使用 CMSIS
            数值，数值越大优先级越高。任务配置中的栈单位为 32-bit words。
            FrameDecode 32 / 384 words / Static，ControlApply 40 / 512 words /
            Dynamic，PanelRender 24 / 384 words / Static。没有 Telemetry 任务。
            FrameQueue 静态容量为 4 个 SensorFrame_t，每元素 16 字节。
            StateLock 是单个静态 mutex，由配置创建，启用优先级继承；不在任务内
            再创建。ControlApply 更新共享快照时使用同一把锁；PanelRender 复制
            后释放锁，I2C 交易期间不持锁。USART2 TX 仅用于上电标识，不是周期任务。

            USART2 RX 使用 DMA1_Channel1 的圆环模式，128 字节；DMA half/full
            回调发布当前位置并置线程标志，帧解析和校验在 FrameDecode 完成。
            标志允许合并，当前位置与环形缓冲消费计数决定实际待处理数据。
            队列满时丢本次完整帧并累计 drops。ControlApply 收到帧时更新 TIM1_CH1
            的占空比和状态，超时只记录失联状态，不自行改变 PWM。TIM1_CH1 的
            2 kHz 波形由硬件产生。PanelRender 使用 I2C 面板，SDA 双向；SCL 为
            主机输出，外设是否拉低延展时钟未确认。
            UI 和 ControlApply 之间只有快照与 StateLock；不存在额外 UI 队列。
            CPU 耗时、调度延迟与总线交易时间均未实测。
        """),
        "current/IDENTITY.json": '{"task_id":"flow-control-29","revision":"r6","modified":"2026-10-08T09:00:00","entry":"FlowController.ioc"}\n',
        "archive/r3/FlowController.ioc": excerpt("""
            # Historical synthetic source; not current.
            MxCube.Version=6.18.1
            Mcu.CPN=STM32G474RET6
            Mcu.Package=LQFP64
            FREERTOS.Tasks01=RxPoll,24,256,RxPoll_Entry,As external,NULL,Dynamic,NULL,NULL;ControlApply,32,384,ControlApply_Entry,As external,NULL,Dynamic,NULL,NULL;Telemetry,16,256,Telemetry_Entry,As external,NULL,Dynamic,NULL,NULL
            FREERTOS.Queues01=FrameQueue,8,SensorFrame_t,0,Dynamic,NULL,NULL
        """),
        "archive/r3/profile.h": "#define configTICK_RATE_HZ 1000U\n#define PANEL_DELAY_TICKS 10U\n",
        "archive/r3/IDENTITY.json": '{"task_id":"flow-control-11","revision":"r3","modified":"2026-10-08T10:30:00","entry":"FlowController.ioc"}\n',
    }))

    result.append(case("03-fpga-single-domain", "串行样本的并行统计与告警",
        "single-clock-fpga-planning",
        "依据现有顶层、约束和模块约定，把这个串行样本监控 FPGA 做成完整规划，交付引脚功能分配和执行逻辑两图。保留当前接口，规划文件写 planning/，不改输入、不运行 Vivado 或硬件。", {
        "constraints/sample_monitor.xdc": excerpt("""
            # Original proposed project constraints; no board measurement.
            set_property PACKAGE_PIN W5 [get_ports clk_100]
            set_property PACKAGE_PIN U18 [get_ports reset_request]
            set_property PACKAGE_PIN B18 [get_ports sample_rx]
            set_property PACKAGE_PIN A18 [get_ports report_tx]
            set_property PACKAGE_PIN U16 [get_ports alive_led]
            set_property PACKAGE_PIN V16 [get_ports alarm_led]
            set_property IOSTANDARD LVCMOS33 [get_ports {clk_100 reset_request sample_rx report_tx alive_led alarm_led}]
            create_clock -name system_clk -period 10.000 [get_ports clk_100]
        """),
        "rtl/sample_monitor_top.sv": excerpt("""
            // Interface excerpt. Module definitions and polarity implementation omitted.
            module sample_monitor_top(
                input wire clk_100, input wire reset_request, input wire sample_rx,
                output wire report_tx, output wire alive_led, output wire alarm_led
            );
                wire reset_internal, sample_valid, five_ms_enable, report_ready;
                wire [15:0] sample_value;
                wire [31:0] latest_total;
                reset_bridge reset_adapter(.clk(clk_100), .request(reset_request),
                                           .reset_out(reset_internal));
                serial_receiver receiver(.clk(clk_100), .rst(reset_internal),
                    .rx(sample_rx), .sample_valid(sample_valid), .sample(sample_value));
                accumulation totals(.clk(clk_100), .rst(reset_internal),
                    .enable(sample_valid), .sample(sample_value), .total(latest_total));
                threshold_alarm alarm(.clk(clk_100), .rst(reset_internal),
                    .enable(sample_valid), .sample(sample_value), .led(alarm_led));
                enable_generator pacing(.clk(clk_100), .rst(reset_internal),
                                        .enable_5ms(five_ms_enable));
                alive_indicator heartbeat(.clk(clk_100), .rst(reset_internal),
                    .step(five_ms_enable), .led(alive_led));
                report_sender reporting(.clk(clk_100), .rst(reset_internal),
                    .request(five_ms_enable), .latest_total(latest_total),
                    .ready(report_ready), .tx(report_tx));
            endmodule
        """),
        "MODULES.md": excerpt("""
            # 原创工程接口约定
            FPGA 器件声明 xc7a35tcpg236-1；全部用户模块使用 clk_100 的同一上升沿。
            sample_rx 是异步串行输入；receiver 内有输入同步与位采样，输出 16 位
            sample_value 和单拍 sample_valid。不把 RX 数据脉冲当作时钟。
            sample_valid 同时使能 totals 与 alarm。二者并行读取同一个样本；
            alarm 不需要等 totals 完成。totals 按 32 位无符号累加回绕。
            pacing 每 500000 拍产生单拍使能。heartbeat 每 40 个该使能翻转一次；
            reporting 遇该使能且 ready 为真时锁存当时 latest_total 并发送。
            reporting 忙时放弃本次请求；不会反压 totals，也没有请求队列。
            如果新 sample_valid 与报告请求同拍，reporting 锁存更新前的 total。

            reset_bridge 实现未随当前材料交付：reset_request 的有效极性、同步
            策略和内部 reset_internal 的有效极性尚未确认。模块约定它统一作用于
            receiver、totals、alarm、pacing、heartbeat 和 reporting；不得据端口名
            推断极性。没有模块仲裁优先级，也没有第二时钟域。
            约束是本项目声明，实际开发板型号、连接器和板测尚未提供。
        """),
    }))

    result.append(case("04-fpga-dual-domain", "FWFT 双域流桥与单一复位源",
        "dual-clock-fwft-planning",
        "根据当前模块边界和接口契约，完成双时钟流桥的整体规划及两张配套图。保留已有 FIFO 与复位接口，不改源码；规划写 planning/。本次不生成 IP、不仿真、不操作硬件。", {
        "rtl/fwft_stream_bridge.sv": excerpt("""
            // Original interface excerpt; the existing FIFO implementation is external.
            module fwft_stream_bridge(
                input wire sample_clk, input wire link_clk,
                input wire fifo_reset,
                input wire [7:0] sample_data, input wire sample_valid,
                output wire sample_ready,
                output wire [7:0] link_data, output wire link_valid,
                input wire link_ready
            );
                wire full, empty, wr_busy, rd_busy;
                wire [7:0] head;
                assign sample_ready = !full && !wr_busy;
                wire push = sample_valid && sample_ready;
                assign link_valid = !empty && !rd_busy;
                assign link_data = head;
                wire pop = link_valid && link_ready;
                existing_fwft_fifo fifo(
                    .wr_clk(sample_clk), .rd_clk(link_clk), .rst(fifo_reset),
                    .din(sample_data), .wr_en(push), .full(full), .wr_rst_busy(wr_busy),
                    .dout(head), .rd_en(pop), .empty(empty), .rd_rst_busy(rd_busy)
                );
            endmodule
        """),
        "constraints/fwft_stream_bridge.xdc": excerpt("""
            # Frequency declarations only. No pin or electrical assignments.
            create_clock -name sample_clk -period 16.000 [get_ports sample_clk]
            create_clock -name link_clk -period 10.000 [get_ports link_clk]
            set_clock_groups -asynchronous -group [get_clocks sample_clk] -group [get_clocks link_clk]
        """),
        "FIFO_CONTRACT.md": excerpt("""
            # 当前已有组件契约
            现有 existing_fwft_fifo 是项目已经选定的黑盒组件，宽 8、深 128。
            本次分析没有其实现源码、器件或生成验证，不能直接当作 XPM 实例。
            sample_clk 为 62.5 MHz，link_clk 为 100 MHz，二者异步。
            sample_data/valid 属于 sample_clk，link_data/valid/ready 属于 link_clk。

            FIFO 是 FWFT：非空且 rd_rst_busy=0 时，队首数据已经在 dout 有效；
            同一 link_clk 上升沿 link_valid && link_ready 为真才消费一个队首。
            不是“先发读请求，下一拍才给出有效数据”。下游反压时队首不变。
            上游在 sample_valid && !sample_ready 时保持 data 和 valid，直到接受。
            wr_en 只在 !full && !wr_rst_busy 时出现；rd_en 只在
            !empty && !rd_rst_busy 且下游 ready 时出现。未定义额外输出缓冲。

            唯一 reset 输入是 fifo_reset，高有效，由 sample_clk 域的上游复位
            控制器提供。控制器属于当前模块边界之外；满足 FIFO 要求的同步输入，
            置位至少 8 个 sample_clk 周期，并保证两时钟持续运行。
            rst 同时请求重置两侧指针；FIFO 内部各自处理其时钟侧释放，分别提供
            wr_rst_busy 和 rd_rst_busy。两侧 busy 可以在不同拍撤销。
            fifo_reset 置位前上游已停止提出数据，下游不再消费；置位期间 busy
            保持有效，复位清空所有在途数据。适配层没有独立用户状态需要复位。
            本接口不允许另增两个外部 reset 引脚，也没有独立的 wr_rst/rd_rst 输入。
            FPGA 型号、封装脚号、电气标准和板卡原理图尚缺；逻辑接口已确定。
        """),
    }))

    result.append(case("05-revision-conflict", "控制板冲突资料与长名称模块",
        "board-conflict-long-label-planning",
        "为现有控制板加入隔离的振动告警输入和故障事件记录，先完成整体规划和两张图。当前工程、板卡交接和需求在目录内。保留已经确定的部分，把影响实施但尚不确定的事项说清楚；不改输入或运行工具，图和说明写 planning/。", {
        "current/ControlGateway.ioc": excerpt("""
            # Original current configuration excerpt; not a verified PCB mapping.
            File.Version=6
            MxCube.Version=6.18.1
            Mcu.CPN=STM32G474RET6
            Mcu.Package=LQFP64
            Mcu.IP0=SPI2
            Mcu.IP1=USART1
            Mcu.IP2=TIM1
            Mcu.IPNb=3
            PB13.Signal=SPI2_SCK
            PB14.Signal=SPI2_MISO
            PB15.Signal=SPI2_MOSI
            PB12.Signal=GPIO_Output
            PB12.GPIO_Label=ISOLATED_SENSOR_CS_N
            PA9.Signal=USART1_TX
            PA10.Signal=USART1_RX
            PA8.Signal=TIM1_CH1
            PA13.Signal=SYS_JTMS-SWDIO
            PA14.Signal=SYS_JTCK-SWCLK
            ProjectManager.ProjectName=ControlGateway
        """),
        "board/assembly-handoff.md": excerpt("""
            # 装配交接
            手中的板卡标签为 CGW-R2A，但提供的连接表标题为 CGW-R1。
            CGW-R1 连接表：隔离传感器使用 SPI1，SCK=PA5 / MISO=PA6 /
            MOSI=PA7 / CS_N=PA4；主机口为 USART2 TX=PA2 / RX=PA3。
            表中 TIM1_CH1=PA8，与 current 配置相同。
            未提供 R2A 原理图、R2A 连接表或可运行工程来源。供应者尚未确认这份
            R1 表能否用于 R2A。新告警隔离器的 MCU 侧输出电压与有效电平未提供。
            不存在已确认可用的 ALERT 引脚或专用复位连接。
        """),
        "current/APP/schedule.h": excerpt("""
            #define SENSOR_POLL_MS 25U
            #define HOST_REPORT_MS 250U
            #define FAULT_RECORD_CAPACITY 8U
        """),
        "current/APP/loop.c": excerpt("""
            void foreground_step(uint32_t now_ms) {
                while (host_has_complete_command()) apply_next_host_command();
                if ((uint32_t)(now_ms - previous_sensor_ms) >= SENSOR_POLL_MS) {
                    previous_sensor_ms = now_ms;
                    latest = poll_isolated_sensor_over_spi2();
                }
                if ((uint32_t)(now_ms - previous_report_ms) >= HOST_REPORT_MS) {
                    previous_report_ms = now_ms;
                    try_send_latest_to_host(&latest);
                }
            }
        """),
        "REQUIREMENTS.md": excerpt("""
            # 已授权的功能目标
            沿用当前裸机主循环，不增加 RTOS。传感器 SPI2 是当前代码路径；板卡
            实际连接仍需匹配资料。主机串口双向，发送忙时跳过当次报告，不补发。
            现有 PWM 1 kHz 由 TIM1_CH1 硬件产生，主机命令可更新占空比。

            新增隔离输入模块“隔离振动告警输入与去抖事件捕获”。发生有效告警后，
            在主循环保存一条时间戳及最近传感器快照，原函数名约定为
            capture_isolated_vibration_alarm_and_store_latest_sensor_snapshot。
            新模块“故障事件循环记录与按主机请求导出”使用容量为 8 的固定内存环；
            满时覆盖最早记录；只有明确的主机导出命令才发送记录。
            模块和连接由本次规划提出，还没有实现。允许把 ISR 缩短为发布事件，
            不要求中断中完成 SPI 或串口传输。去抖窗口、告警输入引脚及有效电平
            尚未确定；不能据材料假定可直接连接 3.3 V GPIO。
            需要继续完成不依赖这些缺口的逻辑规划。CPU 耗时和去抖响应未测量。
        """),
    }))

    result.append(case("06-small-change", "明确范围的边界条件修正",
        "small-change-routing",
        "只修 APP/report_gate.c 中报告边界：达到 REPORT_PERIOD_MS 的当次调用就应允许报告，现在恰好到边界时多等了一次。保留函数接口和其他文件，不改配置，不添加规划图；可以用主机编译器或直接源码检查验证这个局部修改，并如实说明检查方式。不运行厂商工具或硬件。", {
        "APP/report_gate.c": excerpt("""
            #include <stdint.h>
            #include "report_gate.h"
            int report_is_due(uint32_t now_ms, uint32_t last_ms) {
                return (uint32_t)(now_ms - last_ms) > REPORT_PERIOD_MS;
            }
        """),
        "APP/report_gate.h": excerpt("""
            #ifndef REPORT_GATE_H
            #define REPORT_GATE_H
            #include <stdint.h>
            #define REPORT_PERIOD_MS 200U
            int report_is_due(uint32_t now_ms, uint32_t last_ms);
            #endif
        """),
        "BUILD_NOTE.md": excerpt("""
            APP/report_gate.c 是独立纯 C 用户源码，不依赖 HAL 或 RTOS。
            本目录仅包含局部源码，无 Git 仓库、完整工具工程和构建产物。
            返回 true 不会自动更新 last_ms，调用者负责实际发送后更新时间戳。
            只要求达到 200 ms 时允许，不调整参数、不添加任务或延时。
        """),
        "ConfigExcerpt.ioc": "# Synthetic unrelated configuration excerpt.\nMcu.CPN=STM32F103C8T6\nMcu.Package=LQFP48\nProjectManager.ProjectName=GateProbe\n",
    }, writable=["APP/report_gate.c"]))

    result.append(case("07-first-look", "只有配置与代码线索的首次概览",
        "read-only-intake-routing",
        "先只读看懂这个工程：告诉我当前原生入口、基础配置与用户代码的位置、构建线索和若要修改采样队列容量时下一步该从哪里入手。先不改文件、不生成或构建，不需要整体架构设计。", {
        "SensorConsole.ioc": excerpt("""
            # Original synthetic IOC excerpt; newer version has not been validated here.
            File.Version=6
            MxCube.Version=6.19.0
            Mcu.CPN=STM32G474RET6
            Mcu.Package=LQFP64
            Mcu.IP0=FREERTOS
            Mcu.IP1=ADC1
            Mcu.IP2=DMA
            Mcu.IP3=USART2
            Mcu.IPNb=4
            PA0.Signal=ADC1_IN1
            PA2.Signal=USART2_TX
            PA3.Signal=USART2_RX
            FREERTOS.Tasks01=SampleFeed,24,320,SampleFeed_Entry,As external,NULL,Static,FeedStack,FeedTCB;StatsApply,32,448,StatsApply_Entry,As external,NULL,Dynamic,NULL,NULL
            FREERTOS.Queues01=SampleQueue,12,uint32_t,0,Static,SampleBuffer,SampleQueueCB
            ProjectManager.ProjectName=SensorConsole
            ProjectManager.ProjectFileName=SensorConsole.ioc
            ProjectManager.ToolChain=CMake
            ProjectManager.ProjectPath=../retired-lab-copy
        """),
        "CMakeLists.txt": excerpt("""
            cmake_minimum_required(VERSION 3.22)
            project(SensorConsole C ASM)
            set(CMAKE_C_STANDARD 11)
            add_executable(${PROJECT_NAME})
            add_subdirectory(cmake/stm32cubemx)
            target_sources(${PROJECT_NAME} PRIVATE APP/sample_service.c)
            target_link_libraries(${PROJECT_NAME} stm32cubemx)
        """),
        "CMakePresets.json": excerpt("""
            {
              "version": 3,
              "configurePresets": [{"name":"Debug","generator":"Ninja",
                "binaryDir":"${sourceDir}/build/Debug",
                "toolchainFile":"${sourceDir}/cmake/gcc-arm-none-eabi.cmake",
                "cacheVariables":{"CMAKE_BUILD_TYPE":"Debug"}}],
              "buildPresets": [{"name":"Debug","configurePreset":"Debug"}]
            }
        """),
        "cmake/gcc-arm-none-eabi.cmake": excerpt("""
            # Original toolchain declaration excerpt; executables are not included.
            set(CMAKE_SYSTEM_NAME Generic)
            set(CMAKE_SYSTEM_PROCESSOR arm)
            set(CMAKE_C_COMPILER arm-none-eabi-gcc)
            set(CMAKE_ASM_COMPILER arm-none-eabi-gcc)
        """),
        "APP/sample_service.c": excerpt("""
            /* User-owned implementation excerpt; SDK and generated objects omitted. */
            void SampleFeed_Entry(void *argument) {
                for (;;) { send_current_sample_to_generated_queue(); wait_next_sample(); }
            }
            void StatsApply_Entry(void *argument) {
                for (;;) { receive_generated_queue_and_update_statistics(); }
            }
        """),
        "HANDOFF.md": excerpt("""
            这是当前工程目录。IOC 中 ProjectPath 是旧历史字段，不是当前输入来源。
            用户逻辑位于 APP，基础外设和对象结构由 IOC 管理。任务栈字段单位是
            32-bit words；SampleQueue 每元素 uint32_t。摘录没有完整生成目录
            cmake/stm32cubemx、HAL/内核、链接脚本或工具可用性证明。
            当前没有构建、生成或硬件验证结果。只读概览不需要启动这些程序。
        """),
    }))
    return result


def _safe_target(root: Path, name: str) -> Path:
    relative = Path(name)
    target = (root / relative).resolve()
    if relative.is_absolute() or not target.is_relative_to(root):
        raise ValueError("Case path escapes output directory")
    return target


def prepare(output: Path, case_id: str | None = None) -> dict:
    output = output.resolve()
    if output.exists():
        raise ValueError("Output must be a new directory; never overwrite prepared input")
    items = build_cases()
    if case_id is not None:
        items = [item for item in items if item["id"] == case_id]
        if not items:
            raise ValueError("Unknown case id")
    for item in items:
        for name in item["files"]:
            _safe_target(output, name)
    output.mkdir(parents=True)
    records, all_hashes = [], {}
    for item in items:
        target = output if case_id is not None else output / item["id"]
        target.mkdir(exist_ok=True)
        contents = {**item["files"], "REQUEST.md": item["request"] + "\n"}
        hashes = {}
        for name, content in contents.items():
            path = _safe_target(target, name)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
            hashes[name] = hashlib.sha256(path.read_bytes()).hexdigest()
        hashes = dict(sorted(hashes.items()))
        (target / "INPUT-HASHES.json").write_text(
            json.dumps(hashes, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")
        all_hashes[item["id"]] = hashes
        records.append({key: item[key] for key in
                        ["id", "title", "kind", "native_generated", "allowed_source_edits"]}
                       | {"directory": "." if case_id else item["id"],
                          "source_files": sorted(item["files"]), "request_file": "REQUEST.md"})
    manifest = {"schema_version": 1, "suite": "v08b2-original-materials",
                "case_count": len(records), "cases": records,
                "oracle_exported": False, "solutions_or_final_diagrams_created": False,
                "actor_work_policy": "Work on a separate copy. Only case 06 authorizes a source edit."}
    for name, data in [("cases-manifest.json", manifest), ("source-hashes.json", all_hashes)]:
        (output / name).write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n",
                                  encoding="utf-8", newline="\n")
    return {"case_count": len(records), "source_files_hashed": sum(map(len, all_hashes.values())),
            "oracle_exported": False}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--case", help="Prepare one case directly in --output")
    options = parser.parse_args()
    try:
        result = prepare(options.output, options.case)
    except (ValueError, OSError) as exc:
        parser.exit(2, str(exc) + "\n")
    print(json.dumps(result, ensure_ascii=False, indent=2))
